---
# Source:  aws-efs-csi-driver/deploy/kubernetes/base/node-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: efs-csi-node-sa
  namespace: aws-efs-csi-driver
